# -*- coding: utf-8 -*-
"""Monolingual Paraphrase Detection Corpus - Low Resource Sindhi Lang at Sentence Level.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQIfbs7vERWbXmWgOxGsfLYyzwNfVzkG

# LODING DATASET
"""

from google.colab import drive
drive.mount('/content/drive')

# ===============================
# Step 2: Upload your dataset
# ===============================

from google.colab import files
import pandas as pd

# Upload CSV file manually from your local system
uploaded = files.upload()

# Assuming your file name is e.g. "dataset.csv"
df = pd.read_csv(list(uploaded.keys())[0])

# Preview first few rows
df.head()

# ===============================
# Step 3: Basic EDA and column checks
# ===============================

# دیکھیں columns کے نام کیا ہیں
print("Columns:", df.columns.tolist())

# اگر نام مختلف ہیں تو rename کریں
df = df.rename(columns={
    'Sentence1': 'sentence1',
    'Sentence2': 'sentence2',
    'Label': 'label'
})

# Keep only the main labels
df = df[df['label'].isin(['P', 'NP'])].reset_index(drop=True)

# Check again
print("Total rows after filtering:", len(df))
print("Label distribution after filtering:\n", df['label'].value_counts())

# total rows count
print("Total rows:", len(df))

# label distribution
print("\nLabel distribution:")
print(df['label'].value_counts())

# sample دیکھیں
df.sample(5)

"""# CLEANING THE DATA"""

# ===============================
# Step 4: Clean label values
# ===============================

df['label'] = df['label'].astype(str).str.strip().str.upper()

# Replace possible variations
df['label'] = df['label'].replace({
    'PARAPHRASED': 'P',
    'PARAPHRASE': 'P',
    'YES': 'P',
    'NOT_PARAPHRASED': 'NP',
    'NON_PARAPHRASED': 'NP',
    'NO': 'NP'
})

print(df['label'].value_counts())

import re, unicodedata
import pandas as pd

def normalize_text_urdu(s):
    if pd.isna(s):
        return ""
    s = str(s)

    # Unicode normalization
    s = unicodedata.normalize("NFKC", s)

    # Arabic-to-Urdu normalization
    s = s.replace("ي","ی").replace("ى","ی").replace("ك","ک")
    s = s.replace("ہ","ہ").replace("ھ","ہ")
    s = s.replace("إ","ا").replace("أ","ا").replace("آ","ا")
    s = s.replace("ؤ","و").replace("ئ","ی")

    # Remove diacritics
    s = re.sub(r"[\u0610-\u061A\u064B-\u065F\u06D6-\u06ED]", "", s)

    # Remove URLs and HTML
    s = re.sub(r"http\S+|www\.\S+","", s)
    s = re.sub(r"<[^>]+>", "", s)

    # Remove punctuation (keeping Urdu punctuation)
    s = re.sub(r"[^\w\s،۔]", "", s)
    s = re.sub(r"\s+", " ", s).strip()

    return s

# Check actual columns
print("Columns:", df.columns.tolist())

# Check column names
print("Columns available:", df.columns.tolist())

# Try to detect normalized columns
col_s1 = None
col_s2 = None

for c in df.columns:
    if c.lower() in ["s1", "sentence1_norm", "sent1", "clean_s1"]:
        col_s1 = c
    if c.lower() in ["s2", "sentence2_norm", "sent2", "clean_s2"]:
        col_s2 = c

# If not found, fallback to sentence1/sentence2
if col_s1 is None:
    col_s1 = "sentence1"
if col_s2 is None:
    col_s2 = "sentence2"

print("Using columns:", col_s1, col_s2)

# Remove exact duplicates
df = df.drop_duplicates(subset=[col_s1, col_s2, 'label']).reset_index(drop=True)

# Remove reversed duplicates
seen = set()
to_drop = []

for idx, row in df.iterrows():
    a = row[col_s1]
    b = row[col_s2]
    lab = row['label']

    key = (a, b, lab)
    rev = (b, a, lab)

    if rev in seen:
        to_drop.append(idx)
    else:
        seen.add(key)

df = df.drop(index=to_drop).reset_index(drop=True)

print("After removing duplicates:", len(df))

df['s1'] = df['sentence1'].apply(normalize_text_urdu)
df['s2'] = df['sentence2'].apply(normalize_text_urdu)

# ===============================
# Step 7: Remove too short or too long sentences
# ===============================

df['len1'] = df['s1'].str.split().str.len()
df['len2'] = df['s2'].str.split().str.len()

df = df[(df['len1']>=3) & (df['len2']>=3) & (df['len1']<=150) & (df['len2']<=150)]
print("After length filtering:", len(df))

import numpy as np

# ===============================
# Step 8: Check class balance + word statistics for each class
# ===============================

# Total counts
total = len(df)
p_df = df[df['label'] == 'P']
np_df = df[df['label'] == 'NP']

p_count = len(p_df)
np_count = len(np_df)

p_percent = (p_count / total) * 100
np_percent = (np_count / total) * 100

print("📊 Class Balance")
print(f"Total pairs: {total}")
print(f"Paraphrased (P): {p_count} ({p_percent:.2f}%)")
print(f"Non-Paraphrased (NP): {np_count} ({np_percent:.2f}%)")

# ===============================
# Combine both sentences for global text stats
# ===============================
sent_cols = ['sentence1', 'sentence2']
all_text = df[sent_cols[0]].astype(str) + " " + df[sent_cols[1]].astype(str)

# Tokenize words
tokens = " ".join(all_text).split()
unique_words = set(tokens)

# === Calculate metrics ===
total_words = len(tokens)
unique_word_count = len(unique_words)
average_length = np.mean([len(s.split()) for s in all_text])
ttr = unique_word_count / total_words  # Type–Token Ratio

# Word statistics per label
p_text = p_df['sentence1'].astype(str) + " " + p_df['sentence2'].astype(str)
np_text = np_df['sentence1'].astype(str) + " " + np_df['sentence2'].astype(str)

p_word_counts = p_text.apply(lambda x: len(x.split()))
np_word_counts = np_text.apply(lambda x: len(x.split()))

# === Display results ===
print("\n📊 Dataset Statistics")
print(f"Total words: {total_words}")
print(f"Unique words: {unique_word_count}")
print(f"Average sentence length: {average_length:.2f} words")
print(f"Vocabulary richness (TTR): {ttr:.4f}")

print("\n🟢 Paraphrased (P) Word Statistics:")
print(f"Max words: {p_word_counts.max()}")
print(f"Min words: {p_word_counts.min()}")
print(f"Mean words: {p_word_counts.mean():.2f}")
print(f"Median words: {p_word_counts.median():.2f}")

print("\n🔵 Non-Paraphrased (NP) Word Statistics:")
print(f"Max words: {np_word_counts.max()}")
print(f"Min words: {np_word_counts.min()}")
print(f"Mean words: {np_word_counts.mean():.2f}")
print(f"Median words: {np_word_counts.median():.2f}")

# ===============================
# Step 9: Stratified split (80/10/10)
# ===============================

from sklearn.model_selection import train_test_split

train_val, test = train_test_split(df, test_size=0.10, stratify=df['label'], random_state=42)
train, val = train_test_split(train_val, test_size=0.1111, stratify=train_val['label'], random_state=42)

print("Train size:", len(train))
print("Validation size:", len(val))
print("Test size:", len(test))

# Label balance check
print("\nLabel distribution in splits:")
print("Train:\n", train['label'].value_counts(normalize=True))
print("Val:\n", val['label'].value_counts(normalize=True))
print("Test:\n", test['label'].value_counts(normalize=True))

# ===============================
# Step 10: Save cleaned splits
# ===============================

train.to_csv("train_cleaned.csv", index=False)
val.to_csv("val_cleaned.csv", index=False)
test.to_csv("test_cleaned.csv", index=False)

print("✅ All cleaned splits saved successfully in Colab directory.")

# Example: sentence length stats
print("Average length s1:", df['len1'].mean())
print("Average length s2:", df['len2'].mean())

# Basic Urdu script ratio check
def urdu_ratio(text):
    return len(re.findall(r'[\u0600-\u06FF]', str(text))) / max(len(text),1)

df['urdu_ratio_s1'] = df['s1'].apply(urdu_ratio)
df['urdu_ratio_s2'] = df['s2'].apply(urdu_ratio)

print("Average Urdu script coverage:")
print("s1:", df['urdu_ratio_s1'].mean())
print("s2:", df['urdu_ratio_s2'].mean())

"""# TOKENIZE AND ENCODE"""

#1️⃣ Install required libraries
!pip install transformers datasets seqeval -q

# 2️⃣ Imports
import numpy as np
import pandas as pd
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import TrainingArguments, Trainer
from sklearn.metrics import accuracy_score, f1_score, classification_report
from datasets import Dataset

# 3️⃣ Load cleaned CSV splits
train_df = pd.read_csv("train_cleaned.csv")
val_df   = pd.read_csv("val_cleaned.csv")
test_df  = pd.read_csv("test_cleaned.csv")

# 4️⃣ Convert pandas DataFrame to HuggingFace Dataset
train_dataset = Dataset.from_pandas(train_df)
val_dataset   = Dataset.from_pandas(val_df)
test_dataset  = Dataset.from_pandas(test_df)

# 5️⃣ Load the tokenizer (XLM-RoBERTa Base)

from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")

print(train_dataset.column_names)
print(val_dataset.column_names)
print(test_dataset.column_names)

# 6 Tokenization function for sentence pairs

def tokenize_function(examples):
    return tokenizer(
        text=examples['sentence1'],       # must match CSV column
        text_pair=examples['sentence2'],  # must match CSV column
        padding="max_length",
        truncation=True,
        max_length=128
    )

# 7 Apply tokenizer

train_dataset = train_dataset.map(tokenize_function, batched=True)
val_dataset   = val_dataset.map(tokenize_function, batched=True)
test_dataset  = test_dataset.map(tokenize_function, batched=True)

# 4️⃣ Encode labels
label2id = {'P': 1, 'NP': 0}
def encode_labels(example):
    example['labels'] = label2id[example['label']]
    return example

train_dataset = train_dataset.map(encode_labels)
val_dataset   = val_dataset.map(encode_labels)
test_dataset  = test_dataset.map(encode_labels)

# 5️⃣ Keep only required columns
columns_to_keep = ['input_ids', 'attention_mask', 'labels']
train_dataset = train_dataset.remove_columns([c for c in train_dataset.column_names if c not in columns_to_keep])
val_dataset   = val_dataset.remove_columns([c for c in val_dataset.column_names if c not in columns_to_keep])
test_dataset  = test_dataset.remove_columns([c for c in test_dataset.column_names if c not in columns_to_keep])

# 6️⃣ Verify
print(train_dataset.column_names)

# Define the columns the Trainer actually needs
columns_to_keep = ['input_ids', 'attention_mask', 'labels']

# Remove all other columns from the datasets
train_dataset = train_dataset.remove_columns(
    [c for c in train_dataset.column_names if c not in columns_to_keep]
)
val_dataset = val_dataset.remove_columns(
    [c for c in val_dataset.column_names if c not in columns_to_keep]
)
test_dataset = test_dataset.remove_columns(
    [c for c in test_dataset.column_names if c not in columns_to_keep]
)

# Verify
print("Train columns:", train_dataset.column_names)
print("Validation columns:", val_dataset.column_names)
print("Test columns:", test_dataset.column_names)

"""**What just happened??**
You successfully tokenized all your datasets (train, val, test) for sentence pairs.

You also encoded the labels ('P' → 1, 'NP' → 0).

The percentages (100%) and example counts (5679/5679, 710/710) mean that all examples were processed without errors.

**Now that your datasets are ready:**

Load the model (xlm-roberta-base) for sequence classification.

Set training arguments (epochs, learning rate, batch size, evaluation strategy).

Initialize the Trainer from HuggingFace.

Train the model using trainer.train().

Evaluate on validation and test sets to get accuracy and F1-score.

**Sentence pair classification using XLM-RoBERTa.**

# TRAINING THE MODEL
"""

from transformers import AutoModelForSequenceClassification, Trainer, TrainingArguments
import numpy as np
from sklearn.metrics import accuracy_score, f1_score, classification_report

# 1️⃣ Load the model
model_name = "xlm-roberta-base"
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2  # Binary classification: P vs NP
)

# 4️⃣ Load model for sequence classification (binary: P vs NP)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2
)

# 5️⃣ Define metrics function (Accuracy + F1, as in the paper)
def compute_metrics(pred):
    preds = np.argmax(pred.predictions, axis=1)
    labels = pred.label_ids
    acc = accuracy_score(labels, preds)
    f1 = f1_score(labels, preds)
    return {"accuracy": acc, "f1": f1}

!pip install --upgrade transformers -q

import transformers
print(transformers.__version__)

#from transformers import TrainingArguments
#help(TrainingArguments)

#   Define training arguments (compatible with all transformers versions)
training_args = TrainingArguments(
    output_dir="./xlm_roberta_urdu_paper",  # directory to save model & checkpoints
    num_train_epochs=5,                     # number of epochs as per paper
    per_device_train_batch_size=16,         # batch size for training
    per_device_eval_batch_size=16,          # batch size for evaluation
    learning_rate=2e-5,                     # learning rate from paper
    logging_dir="./logs",                    # directory for logs
    logging_steps=50,                        # log every 50 steps
    weight_decay=0.01,                       # weight decay
    overwrite_output_dir=True  ,
    report_to="none",   # MUST BE NONE
 )

# 🔹 Function to compute metrics during evaluation
def compute_metrics(pred):
    preds = np.argmax(pred.predictions, axis=1)  # get predicted class indices
    labels = pred.label_ids                       # true labels
    acc = accuracy_score(labels, preds)          # compute accuracy
    f1 = f1_score(labels, preds)                 # compute F1-score
    return {"accuracy": acc, "f1": f1}

# 🔹 Initialize Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

import os
os.environ["WANDB_DISABLED"] = "true"
os.environ["WANDB_MODE"] = "disabled"

# 🔹 Start training
trainer.train()

# Save model and tokenizer to a folder
save_path = "./xlm_roberta_urdu_paper"
trainer.save_model(save_path)          # saves pytorch_model.bin & config.json
tokenizer.save_pretrained(save_path)   # saves vocab.json, tokenizer_config.json, special_tokens_map.json

# Verify files
!ls ./xlm_roberta_urdu_paper

# 9️⃣ Evaluate on validation set
val_metrics = trainer.evaluate(val_dataset)
print("✅ Validation set metrics:", val_metrics)

# 🔟 Evaluate on test set (final results)
test_metrics = trainer.evaluate(test_dataset)
print("🎯 Test set results:", test_metrics)

# 1️⃣1️⃣ Optional: Detailed classification report
from sklearn.metrics import classification_report

# Get predictions for test set
preds_output = trainer.predict(test_dataset)
pred_labels = np.argmax(preds_output.predictions, axis=1)
true_labels = preds_output.label_ids

print("\n📊 Classification Report on Test Set:")
print(classification_report(true_labels, pred_labels, target_names=['NP', 'P']))

"""# Save the Trained Model to Drive"""

# 🔹 Path in Google Drive where you want to save
save_path_drive = "/content/drive/MyDrive/sindhi_paraphrase_xlmr"

# 🔹 Save the trained model and tokenizer
model.save_pretrained(save_path_drive)
tokenizer.save_pretrained(save_path_drive)

print("✅ Model and tokenizer successfully saved to Google Drive at:", save_path_drive)

# 🔹 Verify files in Drive
!ls /content/drive/MyDrive/sindhi_paraphrase_xlmr

"""# Load model from drive"""

from google.colab import drive
drive.mount('/content/drive')

#Verify the Drive is mounted

!ls "/content/drive/MyDrive"

from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_path = "/content/drive/MyDrive/urdu_paraphrase_xlmr"

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForSequenceClassification.from_pretrained(model_path)

print("✅ Model loaded successfully from Google Drive and ready to use!")

"""`## 📌 PARAPHRASE DETECTION EXPERIMENTS
# N-gram | Word Embedding | Sentence Transformers | Fusion
``

"""

!pip install fasttext-wheel

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, f1_score, accuracy_score
from sklearn.model_selection import train_test_split
from sentence_transformers import SentenceTransformer
import fasttext
import fasttext.util
import warnings
warnings.filterwarnings("ignore")

print("Train label counts:")
print(train["label"].value_counts())

print("\nVal label counts:")
print(val["label"].value_counts())

print("\nTest label counts:")
print(test["label"].value_counts())

"""FASTTEXT WORD EMBEDDING CLASSIFIER
(Averages all word embeddings into a sentence vector)
"""

from sklearn.feature_extraction.text import TfidfVectorizer

# Step 1: Fit TF-IDF on training data
tfidf = TfidfVectorizer()
tfidf.fit(train['text'])
tfidf_vocab = tfidf.vocabulary_

# Step 2: Weighted sentence vector function
def sent_to_vec_weighted(sentence):
    words = sentence.split()
    vecs = []
    weights = []
    for w in words:
        if w in tfidf_vocab:
            vecs.append(ft_model.get_word_vector(w))
            weights.append(tfidf.idf_[tfidf_vocab[w]])  # Use IDF as weight
    if len(vecs) == 0:
        return np.zeros(300)
    return np.average(vecs, axis=0, weights=weights)

# Step 3: Prepare vectors
X_train_ft = np.array([sent_to_vec_weighted(text) for text in train['text']])
X_test_ft  = np.array([sent_to_vec_weighted(text) for text in test['text']])
y_train_ft = train['label']
y_test_ft  = test['label']

# Step 4: Train classifier
clf_ft = LogisticRegression(max_iter=500)
clf_ft.fit(X_train_ft, y_train_ft)

# Step 5: Predict and evaluate
pred_ft = clf_ft.predict(X_test_ft)
from sklearn.metrics import classification_report
print("\n📌 FastText TF-IDF Weighted Results")
print(classification_report(y_test_ft, pred_ft))

"""2) SENTENCE TRANSFORMER CLASSIFIER (ST)
(Produces high-quality sentence embeddings)
"""

print("\n==============================")
print("🏁 Running Sentence Transformer (ST)")
print("==============================")

model_st = SentenceTransformer('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2')

# Convert text to embeddings
X_train_st = model_st.encode(train["text"].tolist(), convert_to_numpy=True)
X_test_st  = model_st.encode(test["text"].tolist(), convert_to_numpy=True)

y_train_st = train["label"]
y_test_st  = test["label"]

# Train classifier
clf_st = LogisticRegression(max_iter=500)
clf_st.fit(X_train_st, y_train_st)

# Predict
pred_st = clf_st.predict(X_test_st)

print("\n📌 ST Results")
print(classification_report(y_test_st, pred_st))

"""FEATURE FUSION = N-GRAM + ST
(Best-performing method according to the paper)

We combine:

TF-IDF N-gram features

Sentence Transformer embeddings

then train one classifier.
"""

print("\n==============================")
print("🏁 Running Feature Fusion (N-Gram + ST)")
print("==============================")

# --- N-gram TF-IDF ---
vectorizer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2)
)

X_train_ng = vectorizer.fit_transform(train["text"]).toarray()
X_test_ng  = vectorizer.transform(test["text"]).toarray()

# --- ST embeddings (already computed above) ---
X_train_fusion = np.hstack([X_train_ng, X_train_st])
X_test_fusion  = np.hstack([X_test_ng,  X_test_st])

# Train classifier
clf_fusion = LogisticRegression(max_iter=1000)
clf_fusion.fit(X_train_fusion, train["label"])

# Predict
pred_fusion = clf_fusion.predict(X_test_fusion)

print("\n📌 Feature Fusion Results (Best)")
print(classification_report(test["label"], pred_fusion))

"""Store predictions when you run each model

N-Gram
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# Prepare TF-IDF vectors
tfidf = TfidfVectorizer(ngram_range=(1,2))
X_train_ngram = tfidf.fit_transform(train['text'])
X_test_ngram  = tfidf.transform(test['text'])

# Train
clf_ngram = LogisticRegression(max_iter=500)
clf_ngram.fit(X_train_ngram, train['label'])

# Predict
pred_ngram = clf_ngram.predict(X_test_ngram)

"""RESULTS TABLE — PRINT CLEAN SUMMARY - Generate F1-score table



"""

from sklearn.metrics import f1_score

def f1(y, p):
    return round(f1_score(y, p, average="weighted"), 4)

results = {
    "Model": ["N-Gram", "FastText WE", "Sentence Transformer", "Feature Fusion"],
    "F1-score": [
        f1(test["label"], pred_ngram),
        f1(y_test_ft, pred_ft),
        f1(y_test_st, pred_st),
        f1(test["label"], pred_fusion),
    ]
}

import pandas as pd
pd.DataFrame(results)

"""Results:
Insights for your research paper

Feature Fusion is the best performing method (F1 = 0.7861).

Shows that combining lexical (N-gram) + semantic (ST) features is highly effective for Urdu paraphrase detection.

N-Gram baseline performs surprisingly well (F1 ≈ 0.772).
Indicates strong lexical similarity patterns in paraphrase pairs.

FastText WE has lower performance (F1 ≈ 0.66).
Word-level embeddings alone are insufficient to capture sentence semantics.

Sentence Transformer (ST) is strong (F1 ≈ 0.745).
Captures context and sentence-level meaning better than word embeddings.

# Zero-shot performance

GPU ran out of memory again while processing all test sentences at once.

We’ll evaluate your model in mini-batches — just like training — so it never overloads GPU memory again.

Instead of sending all ~2,000+ pairs to the GPU at once,
it only sends 16 pairs at a time.

Memory usage stays small, and you’ll never see “CUDA out of memory” again.
Now you have  got your zero-shot results for Spanish (or whichever PAWS-X language you loaded).
Then we can repeat the same code (just changing dataset) for English PAWS-X to complete the cross-lingual comparison like in the research paper.
"""

# You can use google-research-datasets/paws-x which is the official PAWS-X dataset. It covers multiple languages (but does not include Indonesian)

from datasets import load_dataset
dataset = load_dataset("google-research-datasets/paws-x", "en")

!ls /content/drive/MyDrive

"""#Zero-Shot Evaluation on English PAWS-X"""

from datasets import load_dataset
from sklearn.metrics import accuracy_score, f1_score, classification_report
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import numpy as np

# ===============================
# Step 1: Load English PAWS-X dataset
# ===============================
dataset = load_dataset("google-research-datasets/paws-x", "en")

# We'll use the test split for zero-shot evaluation
test_data = dataset["test"]

sent1 = test_data["sentence1"]
sent2 = test_data["sentence2"]
labels = test_data["label"]

# ===============================
# Step 2: Load your fine-tuned Urdu model
# ===============================
model_path = "/content/drive/MyDrive/sindhi_paraphrase_xlmr"  # update if different
tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForSequenceClassification.from_pretrained(model_path)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

# ===============================
# Step 3: Batch inference
# ===============================
batch_size = 16
all_preds = []

for i in range(0, len(sent1), batch_size):
    batch_sent1 = sent1[i:i + batch_size]
    batch_sent2 = sent2[i:i + batch_size]

    inputs = tokenizer(
        batch_sent1,
        batch_sent2,
        truncation=True,
        padding=True,
        max_length=256,
        return_tensors="pt"
    ).to(device)

    with torch.no_grad():
        outputs = model(**inputs)
        preds = torch.argmax(outputs.logits, dim=1).cpu().numpy()
    all_preds.extend(preds)

# ===============================
# Step 4: Metrics
# ===============================
labels = np.array(labels)
all_preds = np.array(all_preds)

acc = accuracy_score(labels, all_preds)
f1 = f1_score(labels, all_preds)

print("✅ Zero-Shot Evaluation (English PAWS-X)")
print(f"Accuracy: {acc:.4f}")
print(f"F1-Score: {f1:.4f}")
print("\nDetailed classification report:")
print(classification_report(labels, all_preds, target_names=["Non-Paraphrase", "Paraphrase"]))

"""# VISUAL RESULTS"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

# =========================
# 1️⃣ Overall metrics
# =========================
val_metrics = {'Accuracy': 0.893, 'F1-score': 0.901, 'Loss': 0.324}
test_metrics = {'Accuracy': 0.903, 'F1-score': 0.909, 'Loss': 0.317}

# Bar chart for Validation vs Test metrics
metrics = ['Accuracy', 'F1-score', 'Loss']
val_scores = [val_metrics[m] for m in metrics]
test_scores = [test_metrics[m] for m in metrics]

x = np.arange(len(metrics))
width = 0.35

plt.figure(figsize=(8,5))
plt.bar(x - width/2, val_scores, width, color='skyblue', label='Validation')
plt.bar(x + width/2, test_scores, width, color='salmon', label='Test')
plt.xticks(x, metrics)
plt.ylabel("Score / Loss")
plt.title("Validation vs Test Metrics")
plt.ylim(0,1)
plt.legend()

# Show values on bars
for i in range(len(metrics)):
    plt.text(i - width/2, val_scores[i]+0.01, f"{val_scores[i]:.2f}", ha='center')
    plt.text(i + width/2, test_scores[i]+0.01, f"{test_scores[i]:.2f}", ha='center')

plt.show()

# =========================
# 2️⃣ Class-wise performance (Test set)
# =========================
# Your classification report data
class_report = {
    'Class': ['NP','P'],
    'Precision': [0.89, 0.91],
    'Recall': [0.90, 0.91],
    'F1-score': [0.90, 0.91],
    'Support': [330, 380]
}

df_report = pd.DataFrame(class_report)

# Bar chart: Precision, Recall, F1 per class
plt.figure(figsize=(8,5))
bar_width = 0.2
r1 = np.arange(len(df_report['Class']))
r2 = [x + bar_width for x in r1]
r3 = [x + bar_width for x in r2]

plt.bar(r1, df_report['Precision'], color='royalblue', width=bar_width, label='Precision')
plt.bar(r2, df_report['Recall'], color='seagreen', width=bar_width, label='Recall')
plt.bar(r3, df_report['F1-score'], color='tomato', width=bar_width, label='F1-score')

plt.xticks([r + bar_width for r in range(len(df_report['Class']))], df_report['Class'])
plt.ylabel("Score")
plt.title("Class-wise Performance on Test Set")
plt.ylim(0,1)
plt.legend()
plt.show()

"""RSEARCH PAPER GRAPHS"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

# =========================
# 1️⃣ Training Loss Curve
# =========================
log_history = trainer.state.log_history
steps = [x['step'] for x in log_history if 'loss' in x]
losses = [x['loss'] for x in log_history if 'loss' in x]

plt.figure(figsize=(8,5))
plt.plot(steps, losses, marker='o', color='tomato')
plt.title("Training Loss Over Steps")
plt.xlabel("Training Steps")
plt.ylabel("Loss")
plt.grid(True)
plt.show()

# =========================
# 4️⃣ Class-wise Heatmap (Optional)
# =========================
heatmap_df = df_report.set_index('Class')[['Precision','Recall','F1-score']]
plt.figure(figsize=(6,4))
sns.heatmap(heatmap_df, annot=True, cmap="YlOrBr", fmt=".2f")
plt.title("Class-wise Metrics Heatmap")
plt.show()

metrics = ['Accuracy', 'F1-score', 'Loss']
val_scores = [val_metrics['Accuracy'], val_metrics['F1-score'], val_metrics['Loss']]
test_scores = [test_metrics['Accuracy'], test_metrics['F1-score'], test_metrics['Loss']]

x = np.arange(len(metrics))
width = 0.35

plt.figure(figsize=(9,5))
plt.bar(x - width/2, val_scores, width, label='Validation', color='skyblue')
plt.bar(x + width/2, test_scores, width, label='Test', color='salmon')
plt.ylim(0,1)
plt.xticks(x, metrics)
plt.ylabel("Score / Loss")
plt.title("Validation vs Test Metrics")
plt.legend()
plt.show()

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

preds_output = trainer.predict(test_dataset)
pred_labels = np.argmax(preds_output.predictions, axis=1)
true_labels = preds_output.label_ids

cm = confusion_matrix(true_labels, pred_labels)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['NP', 'P'])
disp.plot(cmap='Blues')
plt.title("Confusion Matrix - Test Set")
plt.show()

from sklearn.metrics import precision_recall_fscore_support

precision, recall, f1, _ = precision_recall_fscore_support(true_labels, pred_labels)
classes = ['NP', 'P']

x = np.arange(len(classes))
width = 0.2

plt.figure(figsize=(8,5))
plt.bar(x - width, precision, width, label='Precision', color='lightgreen')
plt.bar(x, recall, width, label='Recall', color='orange')
plt.bar(x + width, f1, width, label='F1-score', color='skyblue')
plt.ylim(0,1)
plt.xticks(x, classes)
plt.ylabel("Score")
plt.title("Per-Class Metrics - Test Set")
plt.legend()
plt.show()

from sklearn.metrics import roc_curve, auc

# Get probabilities for class 1
probs = preds_output.predictions[:,1]
fpr, tpr, _ = roc_curve(true_labels, probs)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(7,5))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.2f})')
plt.plot([0,1],[0,1], color='navy', lw=2, linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve - Test Set')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

import seaborn as sns

sns.countplot(pred_labels)
plt.xticks([0,1], ['NP', 'P'])
plt.title("Predicted Class Distribution - Test Set")
plt.show()

"""#Ressearch visuals

figure/table that is publication-ready (high resolution, labeled, annotated) and saved to disk (300 DPI PNG) inside a visuals_for_paper/ folder so you can drop the images straight into your research paper.
"""

# Run this once at the top of the notebook to create the output folder and import libraries
import os
os.makedirs("visuals_for_paper", exist_ok=True)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report, precision_recall_fscore_support, roc_curve, auc

# Styling defaults for publication-ready figures
sns.set(style="whitegrid")
plt.rcParams.update({
    "figure.figsize": (9,5),
    "font.size": 12,
    "axes.titlesize": 14,
    "axes.labelsize": 12
})

print("Setup complete. Output figures will be saved to ./visuals_for_paper/")

"""Training Loss Curve (step-level + epoch eval loss)

This figure shows how training loss changed across steps and (if available) plots validation loss per epoch. Run this after training so trainer.state.log_history exists.
"""

# 1) Training Loss Curve
# Requires: `trainer` to exist with trainer.state.log_history
import numpy as np
import matplotlib.pyplot as plt

out = "visuals_for_paper/training_loss_curve.png"

if 'trainer' not in globals():
    print("trainer object not found. Please run this after training (so trainer.state.log_history exists).")
else:
    log_history = trainer.state.log_history
    # extract step-level training loss
    steps = [entry["step"] for entry in log_history if "loss" in entry]
    losses = [entry["loss"] for entry in log_history if "loss" in entry]

    # extract eval loss per epoch (if available)
    epoch_entries = [entry for entry in log_history if "eval_loss" in entry]
    epochs = [entry.get("epoch") for entry in epoch_entries]
    eval_losses = [entry.get("eval_loss") for entry in epoch_entries]

    fig, ax = plt.subplots(figsize=(10,5))
    ax.plot(steps, losses, label="Training loss (step)", color="#2a9d8f", linewidth=1)
    if eval_losses:
        # scatter eval losses at approximate step positions
        step_positions = np.linspace(min(steps), max(steps), len(eval_losses))
        ax.plot(step_positions, eval_losses, label="Validation loss (per epoch)", color="#e76f51", marker='s')
    ax.set_xlabel("Training steps")
    ax.set_ylabel("Loss")
    ax.set_title("Training Loss Curve")
    ax.grid(alpha=0.25)
    ax.legend()
    plt.tight_layout()
    fig.savefig(out, dpi=300, bbox_inches='tight')
    plt.show()
    print(f"Saved: {out}")

"""2) Validation vs Test Metrics Bar Chart (Accuracy & F1)

This bar chart compares validation and test accuracy & F1. It will use val_metrics and test_metrics if present; otherwise it will use the numbers you printed earlier.
"""

# 2) Validation vs Test metrics bar chart
# Uses val_metrics and test_metrics if available, else uses hard-coded values from your run.

out = "visuals_for_paper/val_vs_test_metrics.png"

# Try to load metrics from session; fallback to reported numbers
val_acc = None
val_f1  = None
test_acc = None
test_f1  = None

if 'val_metrics' in globals():
    val_acc = val_metrics.get('eval_accuracy') or val_metrics.get('accuracy') or val_metrics.get('Accuracy')
    val_f1  = val_metrics.get('eval_f1') or val_metrics.get('f1') or val_metrics.get('F1-score')

if 'test_metrics' in globals():
    test_acc = test_metrics.get('eval_accuracy') or test_metrics.get('accuracy') or test_metrics.get('Accuracy')
    test_f1  = test_metrics.get('eval_f1') or test_metrics.get('f1') or test_metrics.get('F1-score')

# Fallback to the values you shared earlier
if val_acc is None: val_acc = 0.9000
if val_f1 is None:  val_f1  = 0.9079
if test_acc is None: test_acc = 0.9014084507042254
if test_f1 is None:  test_f1  = 0.9081364829396326

labels = ['Accuracy', 'F1-score']
val_vals = [val_acc, val_f1]
test_vals = [test_acc, test_f1]

x = np.arange(len(labels))
width = 0.35

fig, ax = plt.subplots(figsize=(8,5))
rects1 = ax.bar(x - width/2, val_vals, width, label='Validation', color="#264653")
rects2 = ax.bar(x + width/2, test_vals, width, label='Test', color="#2a9d8f")
ax.set_ylim(0,1)
ax.set_xticks(x)
ax.set_xticklabels(labels)
ax.set_ylabel("Score")
ax.set_title("Validation vs Test Metrics")
ax.legend()

# annotate values
for rect in rects1 + rects2:
    h = rect.get_height()
    ax.annotate(f'{h:.2f}', xy=(rect.get_x()+rect.get_width()/2, h), xytext=(0,3),
                textcoords="offset points", ha='center', va='bottom')

plt.tight_layout()
fig.savefig(out, dpi=300, bbox_inches='tight')
plt.show()
print(f"Saved: {out}")

"""3) Confusion Matrix Heatmap (Test set)

This uses preds_output (preferred) or computes predictions using trainer.predict(test_dataset) if needed.
"""

# 3) Confusion matrix heatmap
# Requires preds_output or trainer + test_dataset

out = "visuals_for_paper/confusion_matrix.png"

# Ensure preds are available
if 'preds_output' not in globals():
    if 'trainer' in globals() and 'test_dataset' in globals():
        print("Computing preds_output using trainer.predict(test_dataset) ...")
        preds_output = trainer.predict(test_dataset)
    else:
        raise RuntimeError("No preds_output and cannot compute predictions (trainer or test_dataset missing).")

# Build labels
pred_labels = np.argmax(preds_output.predictions, axis=1)
true_labels = preds_output.label_ids

cm = confusion_matrix(true_labels, pred_labels)
cm_norm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

fig, ax = plt.subplots(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False, ax=ax)
ax.set_xlabel('Predicted label')
ax.set_ylabel('True label')
ax.set_xticklabels(['NP','P'])
ax.set_yticklabels(['NP','P'])
ax.set_title("Confusion Matrix (Test set) — counts")
plt.tight_layout()
fig.savefig(out, dpi=300, bbox_inches='tight')
plt.show()
print(f"Saved: {out}")

# Also save normalized confusion matrix (fraction)
out2 = "visuals_for_paper/confusion_matrix_normalized.png"
fig, ax = plt.subplots(figsize=(6,5))
sns.heatmap(cm_norm, annot=True, fmt='.2f', cmap='Oranges', cbar=True, ax=ax)
ax.set_xlabel('Predicted label')
ax.set_ylabel('True label')
ax.set_xticklabels(['NP','P'])
ax.set_yticklabels(['NP','P'])
ax.set_title("Confusion Matrix (Test set) — normalized")
plt.tight_layout()
fig.savefig(out2, dpi=300, bbox_inches='tight')
plt.show()
print(f"Saved: {out2}")

"""4) Per-class Precision / Recall / F1 (Grouped bar chart)

This builds the table of per-class metrics and displays it as bars. It also prints a nicely formatted table (pandas DataFrame) that you can paste into the paper
"""

# 4) Per-class Precision/Recall/F1 and table for paper
# Uses preds_output or classification_report fallback

out = "visuals_for_paper/per_class_metrics.png"
table_out = "visuals_for_paper/per_class_metrics_table.csv"

if 'preds_output' not in globals():
    if 'trainer' in globals() and 'test_dataset' in globals():
        print("Computing preds_output using trainer.predict(test_dataset) ...")
        preds_output = trainer.predict(test_dataset)
    else:
        raise RuntimeError("No preds_output and cannot compute predictions (trainer or test_dataset missing).")

pred_labels = np.argmax(preds_output.predictions, axis=1)
true_labels = preds_output.label_ids

precisions, recalls, f1s, supports = precision_recall_fscore_support(true_labels, pred_labels, labels=[0,1])
classes = ['NP','P']

# build dataframe
df = pd.DataFrame({
    'class': classes,
    'precision': precisions,
    'recall': recalls,
    'f1': f1s,
    'support': supports
})

# Plot grouped bars
x = np.arange(len(classes))
width = 0.25
fig, ax = plt.subplots(figsize=(8,5))
ax.bar(x - width, df['precision'], width, label='Precision', color='#264653')
ax.bar(x, df['recall'], width, label='Recall', color='#2a9d8f')
ax.bar(x + width, df['f1'], width, label='F1-score', color='#e9c46a')
ax.set_xticks(x)
ax.set_xticklabels(classes)
ax.set_ylim(0,1)
ax.set_ylabel("Score")
ax.set_title("Per-class Precision / Recall / F1 (Test set)")
ax.legend()
for i in range(len(classes)):
    ax.annotate(f"{df['precision'][i]:.2f}", xy=(i - width, df['precision'][i]), xytext=(0,3), textcoords='offset points', ha='center')
    ax.annotate(f"{df['recall'][i]:.2f}", xy=(i, df['recall'][i]), xytext=(0,3), textcoords='offset points', ha='center')
    ax.annotate(f"{df['f1'][i]:.2f}", xy=(i + width, df['f1'][i]), xytext=(0,3), textcoords='offset points', ha='center')

plt.tight_layout()
fig.savefig(out, dpi=300, bbox_inches='tight')
plt.show()
print(f"Saved: {out}")

# Save table CSV for the paper
df.to_csv(table_out, index=False)
print(f"Saved table CSV: {table_out}")
df.style.format({"precision":"{:.2f}","recall":"{:.2f}","f1":"{:.2f}"})

"""5) ROC Curve + AUC and Probability Histogram for positive class

This shows ROC/AUC and distribution of predicted probabilities for class P. Useful for threshold analysis in the paper.
"""

# 5) ROC curve + probability histogram
out_roc = "visuals_for_paper/roc_curve.png"
out_hist = "visuals_for_paper/probability_histogram.png"

# ensure preds_output exists
if 'preds_output' not in globals():
    if 'trainer' in globals() and 'test_dataset' in globals():
        print("Computing preds_output using trainer.predict(test_dataset) ...")
        preds_output = trainer.predict(test_dataset)
    else:
        raise RuntimeError("No preds_output and cannot compute predictions (trainer or test_dataset missing).")

logits = preds_output.predictions  # shape (N,2)
# convert logits to probabilities via softmax
exp_logits = np.exp(logits - np.max(logits, axis=1, keepdims=True))
probs = exp_logits / exp_logits.sum(axis=1, keepdims=True)
pos_probs = probs[:,1]  # probability for positive class (P)
true_labels = preds_output.label_ids

# ROC
fpr, tpr, _ = roc_curve(true_labels, pos_probs)
roc_auc = auc(fpr, tpr)

fig, ax = plt.subplots(figsize=(7,6))
ax.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.3f})')
ax.plot([0,1],[0,1], color='navy', lw=1, linestyle='--')
ax.set_xlim([0.0,1.0]); ax.set_ylim([0.0,1.05])
ax.set_xlabel('False Positive Rate'); ax.set_ylabel('True Positive Rate')
ax.set_title('Receiver Operating Characteristic (ROC)')
ax.legend(loc='lower right')
ax.grid(alpha=0.2)
plt.tight_layout()
fig.savefig(out_roc, dpi=300, bbox_inches='tight')
plt.show()
print(f"Saved: {out_roc}")

# Probability histogram
fig, ax = plt.subplots(figsize=(8,4))
sns.histplot(pos_probs, bins=20, kde=True, color='#2a9d8f', ax=ax)
ax.set_xlabel("Predicted probability for class 'P'")
ax.set_title("Distribution of predicted probabilities (class P)")
plt.tight_layout()
fig.savefig(out_hist, dpi=300, bbox_inches='tight')
plt.show()
print(f"Saved: {out_hist}")

"""6) Key Metrics Table (CSV + pretty printed DataFrame for paper)

This cell assembles a small metrics table (train loss, validation loss, accuracy, F1) and saves it as CSV and PNG (table image for paper).
"""

# 6) Key metrics table and PNG output (safe version)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.table import Table

csv_out = "visuals_for_paper/key_metrics_table.csv"
png_out = "visuals_for_paper/key_metrics_table.png"

# --- Helper function to safely round numbers or replace None ---
def safe_round(x, ndigits=4):
    return round(float(x), ndigits) if isinstance(x, (float, int, np.floating, np.integer)) else "N/A"

# --- Try to gather metrics from your session ---
train_loss_avg = None
if 'trainer' in globals():
    log_history = trainer.state.log_history
    step_losses = [e['loss'] for e in log_history if 'loss' in e]
    if step_losses:
        train_loss_avg = np.mean(step_losses)

val_loss = val_metrics.get('eval_loss') if 'val_metrics' in globals() else None
test_loss = test_metrics.get('eval_loss') if 'test_metrics' in globals() else None

# accuracy & f1
v_acc = None
v_f1  = None
t_acc = None
t_f1  = None

if 'val_metrics' in globals():
    v_acc = val_metrics.get('eval_accuracy') or val_metrics.get('accuracy')
    v_f1  = val_metrics.get('eval_f1') or val_metrics.get('f1')

if 'test_metrics' in globals():
    t_acc = test_metrics.get('eval_accuracy') or test_metrics.get('accuracy')
    t_f1  = test_metrics.get('eval_f1') or test_metrics.get('f1')

# --- Fallbacks to your known results if still None ---
if train_loss_avg is None: train_loss_avg = 0.2869
if val_loss is None: val_loss = 0.3606
if test_loss is None: test_loss = 0.3551
if v_acc is None: v_acc = 0.9000
if v_f1  is None: v_f1  = 0.9079
if t_acc is None: t_acc = 0.9014
if t_f1  is None: t_f1  = 0.9081

# --- Build table ---
table = pd.DataFrame({
    "Metric": [
        "Train loss (avg)",
        "Validation loss",
        "Validation accuracy",
        "Validation F1",
        "Test loss",
        "Test accuracy",
        "Test F1"
    ],
    "Value": [
        safe_round(train_loss_avg),
        safe_round(val_loss),
        safe_round(v_acc),
        safe_round(v_f1),
        safe_round(test_loss),
        safe_round(t_acc),
        safe_round(t_f1)
    ]
})

# --- Save CSV and render as image ---
table.to_csv(csv_out, index=False)
print(f"Saved CSV: {csv_out}")

fig, ax = plt.subplots(figsize=(8,1.6))
ax.axis('off')
tbl = ax.table(cellText=table.values, colLabels=table.columns, cellLoc='center', loc='center')
tbl.auto_set_font_size(False)
tbl.set_fontsize(12)
tbl.scale(1, 2.6)
plt.title("Key Metrics (for paper)")
plt.tight_layout()
fig.savefig(png_out, dpi=300, bbox_inches='tight')
plt.show()
print(f"Saved table image: {png_out}")

"""#TESTING THE MODEL"""

# 🔹 Imports
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# 🔹 Load model & tokenizer
model_path = "/content/xlm_roberta_urdu_paper"
tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForSequenceClassification.from_pretrained(model_path)
model.eval()

# 🔹 Prediction function
def predict_sentence_pair(sentence1, sentence2):
    inputs = tokenizer(
        text=sentence1,
        text_pair=sentence2,
        padding="max_length",
        truncation=True,
        max_length=128,
        return_tensors="pt"
    )

    with torch.no_grad():
        logits = model(**inputs).logits
        predicted_class = torch.argmax(logits, dim=1).item()

    label_map = {0: 'NP', 1: 'P'}
    return label_map[predicted_class]

# 🔹 Example interactive testing
while True:
    print("\nEnter two sentences to classify (type 'exit' to quit):")
    sent1 = input("Sentence 1: ")
    if sent1.lower() == 'exit':
        break
    sent2 = input("Sentence 2: ")
    if sent2.lower() == 'exit':
        break

    prediction = predict_sentence_pair(sent1, sent2)
    print(f"Predicted label: {prediction}")

def predict_with_probs(sentence1, sentence2):
    inputs = tokenizer(
        text=sentence1,
        text_pair=sentence2,
        padding="max_length",
        truncation=True,
        max_length=128,
        return_tensors="pt"
    )

    with torch.no_grad():
        logits = model(**inputs).logits
        probs = torch.softmax(logits, dim=1).squeeze().tolist()
        predicted_class = torch.argmax(logits, dim=1).item()

    label_map = {0: 'NP', 1: 'P'}
    return label_map[predicted_class], probs

label, probs = predict_with_probs(
    "کرکٹ میچ آج منسوخ ہو گیا۔",
    "کھلاڑیوں نے بارش کی وجہ سے کھیل نہیں کھیلا۔"
)
print(f"Predicted label: {label}")
print(f"Probabilities: NP={probs[0]:.2f}, P={probs[1]:.2f}")

"""#MAKING WEBPAGE & HOSTING ONLINE

IMPORTING HUGGING FACE TO COLAB
"""

!pip install huggingface_hub transformers -q

from huggingface_hub import login

# This will prompt you to paste your HuggingFace token
login()

"""Push your model to HuggingFace privately"""

from transformers import AutoTokenizer, AutoModelForSequenceClassification

# Replace 'username' with your HF username
model_name = "mariayasmeen/xlm_roberta_urdu"

# Push model
model.push_to_hub(model_name, private=True)
tokenizer.push_to_hub(model_name, private=True)

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

model_name = "mariayasmeen/xlm_roberta_urdu"

# Load tokenizer and model
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

# Load model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("mariayasmeen/xlm_roberta_urdu")
model = AutoModelForSequenceClassification.from_pretrained("mariayasmeen/xlm_roberta_urdu")

# Prepare sentences
sentence1 = "میرا پہلا جملہ"
sentence2 = "میرا دوسرا جملہ"

# Tokenize
inputs = tokenizer(sentence1, sentence2, padding=True, truncation=True, return_tensors="pt")

# Model prediction
outputs = model(**inputs)
pred = torch.argmax(outputs.logits, dim=1).item()

# Map prediction to label
label = "P" if pred == 1 else "NP"
print("Prediction:", label)